services:
  marketplace_backend:
    container_name: marketplace_backend
    build:
      context: ../
      dockerfile: dev_tools/Dockerfile
    restart: always
    depends_on:
      - marketplace_db
    ports:
      - "8000:8000"
      - "465:465"
    volumes:
      - ../:/app
    networks:
      - marketplace_network
    env_file:
     - .env.dev
    environment:
      ENTRYPOINT_BACKEND: "true"

  marketplace_db:
    container_name: marketplace_db
    image: postgres:alpine
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_marketplace_data:/var/lib/postgresql/data
    networks:
      - marketplace_network

volumes:
  postgres_marketplace_data:

networks:
  marketplace_network:
    external: true
